<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Asp.Versioning.Http" Version="10.2.0" />
    <PackageReference Include="Asp.Versioning.Mvc.ApiExplorer" Version="10.2.0" />
    <PackageReference Include="Microsoft.AspNetCore.OpenApi" Version="10.0.9" />
    <PackageReference Include="Serilog.AspNetCore" Version="10.0.0" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\BiSoft.CarteleraPeliculas.Application\BiSoft.CarteleraPeliculas.Application.csproj" />
    <ProjectReference Include="..\BiSoft.CarteleraPeliculas.Domain\BiSoft.CarteleraPeliculas.Domain.csproj" />
  </ItemGroup>

</Project>
